### ISSUE TITLE
Light effect does not align with cursor when page is scrolled

### ISSUE THREAD

**Issue by anoff** [OpenMined/openmined.org#1]
After the page loads the light source is always at the tip of the cursor. However after scrolling down to the mailing list the light source seems to be off towards the top of the screen.
Is this behaviour intended?

**Comment by cereallarceny** [comment]
No it's not @anoff, I'm working on this and a few other changes I'm yet to document.

**Comment by iamtrask** [comment]
The new site seems to be narrower (vertically)  which significantly reduces the impact of this phenomenon.
