### ISSUE TITLE
Proportions Feedback

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/openmined.org#13]
Love the new brand and the new site! Two points of feedback:
- The size ratio between the text beneath OpenMined and the logo above seems to no longer make a sortof "Diamond" shape in terms of proportions. Just a gut... but the logo might be small relative to the phrase (IMO the logo look REALLY good when its full sized).
- the colors don't seem to be centered like they are in the branding guide. When I fullscreen, the blue and green aren't visible.

**Comment by bennettfarkas** [comment]
What doth github?
To add a few things (IMO);
- the white area should always be at least a meep visible above the fold (on mobile too)
- Per @iamtrask's point, I think the gradient can "stretch" to fit it's container so all the colors are visible all the time.

**Comment by cereallarceny** [comment]
We can adjust sizing manually.  I'm not too concerned about this.  As for the gradient, I think you'll be hard-pressed to get this working perfectly on web without the use of CSS.  Said CSS will take a lot of messing with to get perfect and I won't be able to tackle this until next week (if we even find it necessary by then).

Let me know what you guys want to do.

**Comment by 4mber** [comment]
Let me work with it a bit. Should be able to position the background upwards 50-100px, and then maybe have it move back down via media query when the width is small enough for it to become an issue. Probably the more 'hacky' way to do it, but it might get the job done.

**Comment by iamtrask** [comment]
@cereallarceny Hope your time off goes well! Since it's a significant CSS project I imagine others will be happy to make the change. Possibly tweak sizing as well with the help of the group.

**Comment by cereallarceny** [comment]
Fixed by @4mber
