### ISSUE TITLE
Higher contrast for favicon

### ISSUE THREAD

**Issue by anoff** [OpenMined/openmined.org#14]
On Chrome the favicon lacks a bit of contrast to my taste. Maybe the black version would fit better here?

![image](https://user-images.githubusercontent.com/7142618/29384904-18d8e2b2-82d6-11e7-9faa-32dcc8e805c9.png)

**Comment by cereallarceny** [comment]
I would be fine to have either the white or black background.  @4mber can you take care of this and shoot me a PR with this issue tagged?  I can deploy on Monday should if you remind me.

**Comment by 4mber** [comment]
Will do!

**Comment by cereallarceny** [comment]
Deployed.
