### ISSUE TITLE
New website?

### ISSUE THREAD

**Issue by omaralbeik** [OpenMined/openmined.org#17]
Hey all,

I was wondering if you have any plans for the website?
I can design and implement a new website using React. and a Django admin dashboard for updating it -if needed-.
This will allow us to easily add new features like a banner for announcements, blog, and more in the near future...

**Comment by cereallarceny** [comment]
Hey @omaralbeik - we're working on the design of our website.  We want to keep messaging and branding close to the chest, so we're preferring to keep this internal for now.  Thanks for the offer!

There's plenty of other ways that we're looking for people to contribute.  Feel free to check out for the [contibutor quickstart](https://github.com/OpenMined/Docs/blob/master/contributing/quickstart.md) for more information on that.
