### ISSUE TITLE
Slack channel invite link incorrect

### ISSUE THREAD

**Issue by ChaiBapchya** [OpenMined/openmined.org#21]
For the website - https://openmined.org/
The url - [Slack invite](https://openmined.slack.com/join/shared_invite/enQtMjQzNjExMzkwODgyLTQ5YWNiOWE0OTRkNDhjNDNhOTkwZThjOTJiZWVhOGE1ZGU1Njg0YTRhNWYxZWY1NTZmNWZmY2EyMGI1NjA5N2M
)
returns as 

> This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available.

**Comment by cereallarceny** [comment]
Deployed.
