### ISSUE TITLE
HTTPS ?

### ISSUE THREAD

**Issue by ghost** [OpenMined/openmined.org#6]
This is probably SUPER low on the priorities list, but since the project is all about encryption and user privacy the website should probably be updated to https at some point right? I'm not a web developer, but supposedly it's super easy via Certbot and Let's Encrypt:
- https://certbot.eff.org/
- https://letsencrypt.org/

**Comment by anoff** [comment]
Not sure what @4mber and @cereallarceny are running on but I have good experiences with cloudflare they also provide SSL for your sites..

**Comment by kevinahuber** [comment]
Google also dings search visibility if you are not encrypted. 

If we are on S3 I highly suggest using AWS' Certificate manager- it is cheap and keep everything in the family. I set up a site a couple weeks ago with it, am happy to get that rolling.

**Comment by 4mber** [comment]
Hey all! Spoke to @cereallarceny about this. We're going to wait on the https until we have more online. At the moment it's just a landing page, but once we get the main page up (with all of our branding pinned down, the demos up, etc.), then we can work on the SSL certificate.

**Comment by cereallarceny** [comment]
Thanks for handling this @4mber.  Yep - we're in stealth mode right now and we don't want to show up on Google right now.  Let's focus on the product and leave the site alone.  SSL will definitely come and will be an absolute necessity in a few months, but there's bigger fish to fry.  Gonna close this issue for now.
