### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/openmined.org#7]
It just occurred to me that we are not currently logging where traffic is referred from. This would likely be a very useful resource for understanding who is interested in our community and how people are learning about us.

**Comment by anoff** [comment]
Totally! I could PR this if you want. Is there a special way to set up GA for teams or can I just create one and share it with all of you?
/cc @cereallarceny guess you are more experience in this than I am

**Comment by 4mber** [comment]
They've been added. Thanks!
